# uncomment to send requests:

# GET http://localhost:9000/api/categories

# GET http://localhost:9000/api/reviews/2

# GET http://localhost:9000/api/reviews/9999

# GET http://localhost:9000/api/reviews/not_an_review_id

# PATCH http://localhost:9000/api/reviews/2
#     Content-Type: application/json

#     { "inc_votes": -100 }

# GET http://localhost:9000/api/reviews

# GET http://localhost:9000/api/reviews?category=dexterity&&sort_by=title&&order=asc

# GET http://localhost:9000/api/reviews/2/comments

# POST http://localhost:9000/api/reviews/2/comments
#     Content-Type: application/json

#     { "username": "tickle122", "body": "test" }

# DELETE http://localhost:9000/api/comments/10

# GET http://localhost:9000/api

# GET http://localhost:9000/api/users

GET http://localhost:9000/api/users/grumpy19