# uncomment to send requests:

# GET http://localhost:9000/api/categories

# GET http://localhost:9000/api/reviews/2

# GET http://localhost:9000/api/reviews/9999

# GET http://localhost:9000/api/reviews/not_an_review_id

# GET http://localhost:9000/api/reviews/Monopoly

# GET http://localhost:9000/api/reviews/Culture a Love of Agriculture With Agricola

# PATCH http://localhost:9000/api/reviews/2
#     Content-Type: application/json

#     { "inc_votes": -100 }


# PATCH http://localhost:9000/api/reviews/2
#     Content-Type: application/json

#     { "inc_votes": -100, "review_body": "test" }

# GET http://localhost:9000/api/reviews

# GET http://localhost:9000/api/reviews?category=dexterity&&sort_by=title&&order=asc

# GET http://localhost:9000/api/reviews/2/comments

# POST http://localhost:9000/api/reviews/2/comments
#     Content-Type: application/json

#     { "username": "tickle122", "body": "test" }

# DELETE http://localhost:9000/api/comments/10

# GET http://localhost:9000/api

# GET http://localhost:9000/api/users

# GET http://localhost:9000/api/users/grumpy19

# PATCH http://localhost:9000/api/comments/2
#     Content-Type: application/json

#     { "inc_votes": 1 }

# PATCH http://localhost:9000/api/comments/1
#     Content-Type: application/json

#     { "inc_votes": 1, "body": "edited!" }


# GET http://localhost:9000/api/reviews?limit=8&&p=99

# POST http://localhost:9000/api/reviews
#     Content-Type: application/json

#     {
#     "title": "A test",
#     "designer": "Uwe Rosenberg",
#     "owner": "tickle122",
#     "review_body": "Farmyard fun!",
#     "category": "strategy"
#   }

# POST http://localhost:9000/api/categories
#     Content-Type: application/json

#     {
#     "slug": "Test",
#     "description": "this is a test"
#   }


# DELETE http://localhost:9000/api/reviews/9999


# POST http://localhost:9000/api/users
#     Content-Type: application/json

#     {
#     "username": "testusername123",
#     "name": "Jane Doe",
#     "avatar_url": "https://vignette.wikia.nocookie.net/mrmen/images/4/4f/MR_JELLY_4A.jpg/revision/latest?cb=20180104121141"
#   }


PATCH http://localhost:9000/api/users/grumpy19
    Content-Type: application/json

    {
    "name": "Jane Doe",
    "avatar_url": "https://vignette.wikia.nocookie.net/mrmen/images/4/4f/MR_JELLY_4A.jpg/revision/latest?cb=20180104121141"
  }